# Generated by Django 4.1.2 on 2022-10-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.CharField(max_length=255)),
                ('animeTitle', models.CharField(max_length=255)),
                ('animeImg', models.CharField(max_length=450)),
                ('synopsis', models.CharField(max_length=3000)),
                ('MangaTitle', models.CharField(max_length=255)),
                ('MangaCover', models.CharField(max_length=450)),
                ('MangaSynopsis', models.CharField(max_length=3000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
